# This app.yaml is for deploying to instances of Cloud SQL running MySQL.
# See app-postgres.yaml for running Cloud SQL with PostgreSQL.

# [START gae_cloudsql_mysql_env]
runtime: php72

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER: "root"
  CLOUDSQL_PASSWORD: [SECRET_CLOUDSQL_PASSWORD]
  CLOUDSQL_DSN: "mysql:dbname=dft-ddt-teanbiscuits-dev;unix_socket=/cloudsql/apszaz-dft-cicd:europe-west2:ddt-nonprod"
# [END gae_cloudsql_mysql_env]

