steps:

# Decrypt the secrets file
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets-${_DST_ENVIRONMENT}.sh.enc
  - --plaintext-file=secrets.sh
  - --location=global
  - --keyring=CLOUDBUILD-SECRETS
  - --key=CLOUDBUILD-KEY
  - --project=${_DST_PROJECT}

# Do whatever is needed before deploying the app
- name: 'ubuntu'
  args: ['bash', './build.sh']
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'TAG=$TAG_NAME'

# Deploy app to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', '${_DST_PROJECT}']

